enabled_default: 0
default_challenge: recaptcha_v3/captcha_action
description: 'The answer you entered for the CAPTCHA was not correct.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: false
default_validation: 1
persistence: 0
enable_stats: false
log_wrong_responses: true
_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
